name: norse-venture-backend
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Only deploy master
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run production migration
        run: npm run migrate:postgres
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
