name: norse-venture-backend
on:
  push:
    branches: [master]

jobs:
  migration:
    name: prisma migration to master branch postgres DB
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: npx pnpm install
      - name: Copy env file
        run: |
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env
      - name: Run production migration
        run: npx pnpm migrate:postgres
