name: norse-venture-backend
on:
  push:
    branches: [master]

jobs:
  migration:
    name: prisma migration to master branch postgres DB
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: sudo npm i -g pnpm
      - run: pnpm install
      - name: Copy env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" >> .env
      - name: Run production migration
        run: npx pnpm migrate:postgres
      - name: Build
        run: pnpx prisma generate && pnpm run build
