name: norse-venture-backend
on:
  push:
    branches: [master]

jobs:
  migration:
    name: prisma migration to master branch postgres DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx pnpm install
      - name: Run production migration
        run: npx pnpm migrate:postgres
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
